// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYQIFbTbMCnD-U0D1v-HbObp8XLX0haw',
    appId: '1:96461467719:web:b72455fed1ff085909c162',
    messagingSenderId: '96461467719',
    projectId: 'flutter-mcp-671e5',
    authDomain: 'flutter-mcp-671e5.firebaseapp.com',
    storageBucket: 'flutter-mcp-671e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpaRtsDS71Nx7m2ebKHRFdb5_XgzfiItk',
    appId: '1:96461467719:android:3952deec0fe499a709c162',
    messagingSenderId: '96461467719',
    projectId: 'flutter-mcp-671e5',
    storageBucket: 'flutter-mcp-671e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bBNyWy6GTIh1QvNGio2FY3LdLPynSkE',
    appId: '1:96461467719:ios:0e6e295f1d5aa24309c162',
    messagingSenderId: '96461467719',
    projectId: 'flutter-mcp-671e5',
    storageBucket: 'flutter-mcp-671e5.firebasestorage.app',
    iosBundleId: 'com.example.receiptValidator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bBNyWy6GTIh1QvNGio2FY3LdLPynSkE',
    appId: '1:96461467719:ios:0e6e295f1d5aa24309c162',
    messagingSenderId: '96461467719',
    projectId: 'flutter-mcp-671e5',
    storageBucket: 'flutter-mcp-671e5.firebasestorage.app',
    iosBundleId: 'com.example.receiptValidator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrYQIFbTbMCnD-U0D1v-HbObp8XLX0haw',
    appId: '1:96461467719:web:182fde54b0a8ec1a09c162',
    messagingSenderId: '96461467719',
    projectId: 'flutter-mcp-671e5',
    authDomain: 'flutter-mcp-671e5.firebaseapp.com',
    storageBucket: 'flutter-mcp-671e5.firebasestorage.app',
  );
}
